FROM public.ecr.aws/lambda/python:3.11

# Install OS-level packages
RUN yum install -y \
    libgomp \
    libstdc++ \
    gcc \
    glibc \
    glibc-devel \
    && yum clean all

# Set working dir
WORKDIR /var/task

# Copy requirements and install
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy your source code and .so
COPY ./lambda_package/ .
COPY ./lambda_package/libbaf2sql_c.so .

# Set the entry point
CMD ["lambda_handler.handler"]