#!/usr/bin/env python3
"""
NetCDF Output Validation Script for Bruker .d to NetCDF Converter

This script validates the NetCDF output files generated by the converter,
checking both structure and data quality.

Expected Output Format:
- Time-domain: dimensions [swim_id, mass_charge], data variable 'intensity' (int)
- Fourier-domain: dimensions [frequency, mass_charge], data variable 'amplitude' (float32)

Usage:
    python validate_netcdf.py <file_path> [options]
    python validate_netcdf.py <directory> --batch [options]

Exit codes:
    0: All validations passed
    1: Validation failures detected
    2: Error opening or reading file
"""

import argparse
import sys
import json
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import numpy as np
import xarray as xr


class ValidationResult:
    """Container for validation results."""

    def __init__(self, file_path: str):
        self.file_path = file_path
        self.passed = True
        self.errors = []
        self.warnings = []
        self.info = {}

    def add_error(self, message: str):
        """Add an error (causes validation failure)."""
        self.errors.append(message)
        self.passed = False

    def add_warning(self, message: str):
        """Add a warning (doesn't cause failure but noteworthy)."""
        self.warnings.append(message)

    def add_info(self, key: str, value):
        """Add informational data."""
        self.info[key] = value

    def to_dict(self) -> Dict:
        """Convert to dictionary for JSON output."""
        return {
            "file_path": self.file_path,
            "passed": self.passed,
            "errors": self.errors,
            "warnings": self.warnings,
            "info": self.info
        }

    def print_summary(self, verbose: bool = False):
        """Print human-readable summary."""
        status = "✓ PASSED" if self.passed else "✗ FAILED"
        print(f"\n{status}: {self.file_path}")

        if self.errors:
            print(f"  Errors ({len(self.errors)}):")
            for error in self.errors:
                print(f"    - {error}")

        if self.warnings:
            print(f"  Warnings ({len(self.warnings)}):")
            for warning in self.warnings:
                print(f"    - {warning}")

        if verbose and self.info:
            print(f"  Information:")
            for key, value in self.info.items():
                print(f"    {key}: {value}")


class NetCDFValidator:
    """Validator for NetCDF output files."""

    def __init__(self, verbose: bool = False):
        self.verbose = verbose

    def detect_file_type(self, ds: xr.Dataset) -> Optional[str]:
        """
        Detect if file is time-domain or Fourier-domain based on dimensions.

        Returns:
            'time_domain', 'fourier_domain', or None if unrecognized
        """
        dims = set(ds.sizes.keys())

        if 'swim_id' in dims and 'mass_charge' in dims:
            return 'time_domain'
        elif 'frequency' in dims and 'mass_charge' in dims:
            return 'fourier_domain'
        else:
            return None

    def validate_structure_time_domain(self, ds: xr.Dataset, result: ValidationResult):
        """Validate structure of time-domain NetCDF file."""

        # Check dimensions
        if 'swim_id' not in ds.sizes:
            result.add_error("Missing required dimension: 'swim_id'")
        else:
            result.add_info("swim_id_length", ds.sizes['swim_id'])

        if 'mass_charge' not in ds.sizes:
            result.add_error("Missing required dimension: 'mass_charge'")
        else:
            result.add_info("mass_charge_length", ds.sizes['mass_charge'])

        # Check data variable
        if 'intensity' not in ds.data_vars:
            result.add_error("Missing required data variable: 'intensity'")
        else:
            intensity = ds['intensity']

            # Check data type
            if not np.issubdtype(intensity.dtype, np.integer):
                result.add_error(f"Expected integer dtype for 'intensity', got {intensity.dtype}")
            else:
                result.add_info("intensity_dtype", str(intensity.dtype))

            # Check shape
            expected_shape = (ds.sizes.get('swim_id', 0), ds.sizes.get('mass_charge', 0))
            if intensity.shape != expected_shape:
                result.add_error(f"Data shape {intensity.shape} doesn't match dimensions {expected_shape}")

        # Check coordinates
        if 'swim_id' in ds.coords:
            swim_ids = ds.coords['swim_id'].values

            # Check if swim_id starts at 1
            if len(swim_ids) > 0 and swim_ids[0] != 1:
                result.add_warning(f"swim_id starts at {swim_ids[0]}, expected to start at 1")

            # Check if swim_id is sequential
            expected_ids = np.arange(1, len(swim_ids) + 1)
            if not np.array_equal(swim_ids, expected_ids):
                result.add_warning("swim_id coordinates are not sequential integers starting from 1")

        if 'mass_charge' in ds.coords:
            mz = ds.coords['mass_charge'].values
            result.add_info("mass_charge_range", f"{mz.min():.2f} - {mz.max():.2f}")

            # Check if m/z values are reasonable (typical range 50-2000 for mass spec)
            if mz.min() < 1 or mz.max() > 10000:
                result.add_warning(f"mass_charge range ({mz.min():.2f} - {mz.max():.2f}) is unusual for mass spectrometry")

    def validate_structure_fourier_domain(self, ds: xr.Dataset, result: ValidationResult):
        """Validate structure of Fourier-domain NetCDF file."""

        # Check dimensions
        if 'frequency' not in ds.sizes:
            result.add_error("Missing required dimension: 'frequency'")
        else:
            result.add_info("frequency_length", ds.sizes['frequency'])

        if 'mass_charge' not in ds.sizes:
            result.add_error("Missing required dimension: 'mass_charge'")
        else:
            result.add_info("mass_charge_length", ds.sizes['mass_charge'])

        # Check data variable
        if 'amplitude' not in ds.data_vars:
            result.add_error("Missing required data variable: 'amplitude'")
        else:
            amplitude = ds['amplitude']

            # Check data type
            if amplitude.dtype != np.float32:
                result.add_warning(f"Expected float32 dtype for 'amplitude', got {amplitude.dtype}")
            else:
                result.add_info("amplitude_dtype", str(amplitude.dtype))

            # Check shape
            expected_shape = (ds.sizes.get('frequency', 0), ds.sizes.get('mass_charge', 0))
            if amplitude.shape != expected_shape:
                result.add_error(f"Data shape {amplitude.shape} doesn't match dimensions {expected_shape}")

        # Check coordinates
        if 'frequency' in ds.coords:
            freq = ds.coords['frequency'].values
            result.add_info("frequency_range", f"{freq.min():.6f} - {freq.max():.6f}")

            # Check if frequency starts at 0 (DC component)
            if len(freq) > 0 and freq[0] != 0:
                result.add_warning(f"frequency starts at {freq[0]}, expected to start at 0")

            # Check if frequencies are non-negative (rfft output)
            if np.any(freq < 0):
                result.add_error("Negative frequencies found (expected rfft output with non-negative frequencies)")

        if 'mass_charge' in ds.coords:
            mz = ds.coords['mass_charge'].values
            result.add_info("mass_charge_range", f"{mz.min():.2f} - {mz.max():.2f}")

            # Check if m/z values are reasonable
            if mz.min() < 1 or mz.max() > 10000:
                result.add_warning(f"mass_charge range ({mz.min():.2f} - {mz.max():.2f}) is unusual for mass spectrometry")

    def validate_data_quality(self, ds: xr.Dataset, file_type: str, result: ValidationResult):
        """Validate data quality for both file types."""

        var_name = 'intensity' if file_type == 'time_domain' else 'amplitude'

        if var_name not in ds.data_vars:
            return  # Already reported as error in structure validation

        data = ds[var_name].values

        # Check for NaN values
        nan_count = np.isnan(data).sum()
        if nan_count > 0:
            result.add_error(f"Found {nan_count} NaN values in {var_name}")

        # Check for infinity values
        inf_count = np.isinf(data).sum()
        if inf_count > 0:
            result.add_error(f"Found {inf_count} infinite values in {var_name}")

        # Check for negative values (physically impossible for intensities/amplitudes)
        negative_count = (data < 0).sum()
        if negative_count > 0:
            result.add_error(f"Found {negative_count} negative values in {var_name} (physically invalid)")

        # Check for all-zero rows or columns
        if data.ndim == 2:
            zero_rows = np.all(data == 0, axis=1).sum()
            zero_cols = np.all(data == 0, axis=0).sum()

            if zero_rows > 0:
                result.add_warning(f"Found {zero_rows} all-zero rows (may indicate extraction issues)")

            if zero_cols > 0:
                result.add_warning(f"Found {zero_cols} all-zero columns (may indicate extraction issues)")

        # Check if data is all zeros
        if np.all(data == 0):
            result.add_error("All data values are zero (likely indicates extraction failure)")

        # Add statistics
        result.add_info(f"{var_name}_min", float(data.min()))
        result.add_info(f"{var_name}_max", float(data.max()))
        result.add_info(f"{var_name}_mean", float(data.mean()))
        result.add_info(f"{var_name}_nonzero_count", int((data != 0).sum()))
        result.add_info(f"{var_name}_total_count", int(data.size))

    def validate_file(self, file_path: str) -> ValidationResult:
        """
        Validate a single NetCDF file.

        Args:
            file_path: Path to the NetCDF file

        Returns:
            ValidationResult object
        """
        result = ValidationResult(file_path)

        # Try to open the file
        try:
            ds = xr.open_dataset(file_path)
        except Exception as e:
            result.add_error(f"Failed to open file: {e}")
            return result

        try:
            # Detect file type
            file_type = self.detect_file_type(ds)

            if file_type is None:
                result.add_error("Unrecognized file structure (expected time_domain or fourier_domain)")
                return result

            result.add_info("file_type", file_type)

            # Validate structure based on file type
            if file_type == 'time_domain':
                self.validate_structure_time_domain(ds, result)
            elif file_type == 'fourier_domain':
                self.validate_structure_fourier_domain(ds, result)

            # Validate data quality
            self.validate_data_quality(ds, file_type, result)

        finally:
            ds.close()

        return result

    def validate_paired_files(self, time_domain_path: str, fourier_domain_path: str) -> ValidationResult:
        """
        Validate a pair of time-domain and Fourier-domain files for consistency.

        Args:
            time_domain_path: Path to time-domain NetCDF file
            fourier_domain_path: Path to Fourier-domain NetCDF file

        Returns:
            ValidationResult object
        """
        result = ValidationResult(f"Paired: {time_domain_path} + {fourier_domain_path}")

        try:
            ds_time = xr.open_dataset(time_domain_path)
            ds_fourier = xr.open_dataset(fourier_domain_path)
        except Exception as e:
            result.add_error(f"Failed to open paired files: {e}")
            return result

        try:
            # Check mass_charge coordinates match
            if 'mass_charge' in ds_time.coords and 'mass_charge' in ds_fourier.coords:
                mz_time = ds_time.coords['mass_charge'].values
                mz_fourier = ds_fourier.coords['mass_charge'].values

                if not np.array_equal(mz_time, mz_fourier):
                    result.add_error("mass_charge coordinates don't match between time and Fourier domain files")
                else:
                    result.add_info("mass_charge_match", True)

            # Check expected relationship between swim_id and frequency dimensions
            if 'swim_id' in ds_time.sizes and 'frequency' in ds_fourier.sizes:
                swim_id_count = ds_time.sizes['swim_id']
                freq_count = ds_fourier.sizes['frequency']
                expected_freq_count = swim_id_count // 2 + 1

                if freq_count != expected_freq_count:
                    result.add_error(
                        f"Frequency dimension size ({freq_count}) doesn't match expected "
                        f"rfft output size ({expected_freq_count}) for swim_id count ({swim_id_count})"
                    )
                else:
                    result.add_info("frequency_dimension_match", True)

        finally:
            ds_time.close()
            ds_fourier.close()

        return result


def find_paired_file(file_path: Path) -> Optional[Path]:
    """
    Find the paired file (time-domain <-> Fourier-domain).

    Args:
        file_path: Path to one of the files

    Returns:
        Path to paired file if found, None otherwise
    """
    if '_timedomain.nc' in file_path.name:
        paired = file_path.parent / file_path.name.replace('_timedomain.nc', '_fourierdomain.nc')
    elif '_fourierdomain.nc' in file_path.name:
        paired = file_path.parent / file_path.name.replace('_fourierdomain.nc', '_timedomain.nc')
    else:
        return None

    return paired if paired.exists() else None


def main():
    parser = argparse.ArgumentParser(
        description='Validate NetCDF output files from Bruker .d to NetCDF converter',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    parser.add_argument(
        'path',
        help='Path to NetCDF file or directory containing NetCDF files'
    )

    parser.add_argument(
        '--batch',
        action='store_true',
        help='Process all .nc files in the specified directory'
    )

    parser.add_argument(
        '--check-pairs',
        action='store_true',
        help='Also validate paired time-domain and Fourier-domain files for consistency'
    )

    parser.add_argument(
        '--json',
        action='store_true',
        help='Output results as JSON'
    )

    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Print detailed information about each file'
    )

    args = parser.parse_args()

    validator = NetCDFValidator(verbose=args.verbose)
    path = Path(args.path)

    # Collect files to validate
    files_to_validate = []

    if not path.exists():
        print(f"Error: Path does not exist: {path}", file=sys.stderr)
        return 2

    if path.is_file():
        if not path.suffix == '.nc':
            print(f"Error: File must have .nc extension: {path}", file=sys.stderr)
            return 2
        files_to_validate.append(path)
    elif path.is_dir():
        if args.batch:
            files_to_validate = sorted(path.glob('*.nc'))
            if not files_to_validate:
                print(f"Error: No .nc files found in directory: {path}", file=sys.stderr)
                return 2
        else:
            print(f"Error: {path} is a directory. Use --batch to process all files in directory", file=sys.stderr)
            return 2
    else:
        print(f"Error: Invalid path: {path}", file=sys.stderr)
        return 2

    # Validate files
    results = []
    for file_path in files_to_validate:
        result = validator.validate_file(str(file_path))
        results.append(result)

    # Validate paired files if requested
    paired_results = []
    if args.check_pairs:
        processed_pairs = set()
        for file_path in files_to_validate:
            paired_path = find_paired_file(file_path)
            if paired_path:
                # Create a tuple to avoid processing the same pair twice
                pair_key = tuple(sorted([str(file_path), str(paired_path)]))
                if pair_key not in processed_pairs:
                    processed_pairs.add(pair_key)
                    paired_result = validator.validate_paired_files(str(file_path), str(paired_path))
                    paired_results.append(paired_result)

    # Output results
    if args.json:
        output = {
            "individual_files": [r.to_dict() for r in results],
            "paired_files": [r.to_dict() for r in paired_results],
            "summary": {
                "total_files": len(results),
                "passed": sum(1 for r in results if r.passed),
                "failed": sum(1 for r in results if not r.passed),
                "total_pairs": len(paired_results),
                "pairs_passed": sum(1 for r in paired_results if r.passed),
                "pairs_failed": sum(1 for r in paired_results if not r.passed)
            }
        }
        print(json.dumps(output, indent=2))
    else:
        # Print individual file results
        for result in results:
            result.print_summary(verbose=args.verbose)

        # Print paired file results
        for result in paired_results:
            result.print_summary(verbose=args.verbose)

        # Print summary
        total = len(results)
        passed = sum(1 for r in results if r.passed)
        failed = total - passed

        print(f"\n{'='*60}")
        print(f"Summary: {passed}/{total} files passed validation")

        if paired_results:
            pairs_total = len(paired_results)
            pairs_passed = sum(1 for r in paired_results if r.passed)
            pairs_failed = pairs_total - pairs_passed
            print(f"Paired validation: {pairs_passed}/{pairs_total} pairs passed")

        print(f"{'='*60}")

    # Exit with appropriate code
    all_passed = all(r.passed for r in results) and all(r.passed for r in paired_results)
    return 0 if all_passed else 1


if __name__ == '__main__':
    sys.exit(main())
