name: Run Remote Job

on:
  push:
    paths:
      - 'jobs/job_*.json'

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install numpy xarray pyfftw
      - run: python job_runner.py